### ISSUE TITLE
请问不支持行内数学公式吗？

### ISSUE THREAD

**Issue by bwangelme** [laozhu/hugo-nuo#10]
你好，首先非常感谢您提供这么好用的主题，这让我的生活方便了好多，但是我在使用主题的时候遇到了一个小问题。

有时候我需要某些数学公式需要在行内显示，而不是占一整行，我看 MathJax 是通过`$公式内容$`的形式实现的。但是我看`hugo-nuo`主题好像不支持这种形式，所以想请教一下该如何开启这个功能？

**Comment by laozhu** [comment]
确实存在这个问题，我明天解决下。

**Comment by laozhu** [comment]
@bwangel23 问题已经解决了 (Inline MathJax Formula)，问题的原因是 `$...$` 默认没有被开启，😆

> The default math delimiters are $$...$$ and \[...\] for displayed mathematics, and \(...\) for in-line mathematics. Note in particular that the $...$ in-line delimiters are not used by default. That is because dollar signs appear too often in non-mathematical settings, which could cause some text to be treated as mathematics unexpectedly.

[Detail 详情](http://docs.mathjax.org/en/latest/start.html#tex-and-latex-input)  | [Demo 演示](https://laozhu.me/post/hugo-nuo-post-preview/#inline-mathjax)

**Comment by bwangelme** [comment]
赞一个，感谢楼主。
