### ISSUE TITLE
pages never get refreshed once cached by service worker

### ISSUE THREAD

**Issue by loveky** [laozhu/hugo-nuo#101]
Based on the current implementation, once a request is cached by the service worker, it will not be updated unless we update the `cacheName` variable manually.

I think we should find an automatic way to update the cacheName on every build. Any ideas?

**Comment by laozhu** [comment]
Hi, @loveky, I searched for two methods:

- Generate new `service-worker.js` file when hugo build (with [sw-precache](https://github.com/GoogleChromeLabs/sw-precache))
- Replace `cache-first` with `network-first` strategy

But I don't like depending on node and npm environment to build, any good ideas to share with me :)

**Comment by loveky** [comment]
Yes, I can see your concern about depending on node/npm.

How about making the service worker `network-first`?

```js
// network first
self.addEventListener('fetch', event => {
  event.respondWith(
    caches.open(cacheName).then(function(cache) {
      return fetch(event.request)
        .then(function(response) {
          if (response.status === 404) return caches.match('404.html');
          cache.put(event.request, response.clone());
          return response;
        })
        .catch(function() {
          return caches.match(event.request);
        });
    }),
  );
});
```

**Comment by loveky** [comment]
I have applied it to my blog, seems working 😄

**Comment by laozhu** [comment]
@loveky Thanks for your share, your code works great! I think network-first is OK, but cache-first means better performance and less loading time, I will keep cache-first strategy and try to regenerate new `service-worker.js` with hugo only.

I found that hugo supports  [Custom Output Formats](https://gohugo.io/templates/output-formats/), If we can use hugo variables in `service-worker.js`, we can make this file change with every hugo build.

I will deep in this tonight 😄

**Comment by laozhu** [comment]
Asking for help https://github.com/gohugoio/hugo/issues/5495

**Comment by laozhu** [comment]
@loveky I have given up with your network-first strategy 😄

**Comment by loveky** [comment]
Got it. we can leverage that before we get a better solution.

**Comment by samuelkarp** [comment]
> If we can use hugo variables in `service-worker.js`, we can make this file change with every hugo build.

Commit ac11c7d (part of https://github.com/laozhu/hugo-nuo/pull/118) enables Hugo variables inside `service-worker.js`.
