### ISSUE TITLE
Change the avatar frame from circle to hexagon

### ISSUE THREAD

**Issue by Edouard-Legoupil** [laozhu/hugo-nuo#105]
Hi - 

I would like to slightly change the theme by changing the avatar frame from a circle to an hexagon - (using something like https://github.com/cran/hexSticker )

Any quick hint on how to do that?

Thanks a lot!
Edouard

**Comment by laozhu** [comment]
@Edouard-Legoupil Make it with CSS [clip-path](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path)

1. Generate hexagon clip-path by <http://bennettfeely.com/clippy/>
2. Remove border and border-radius, add clip-path

![image](https://user-images.githubusercontent.com/1212457/50844779-74684480-13a6-11e9-9e19-4d45f8245971.png)

3. It seems OK for mine
 
![image](https://user-images.githubusercontent.com/1212457/50844871-9b267b00-13a6-11e9-905b-d52549ad9d0d.png)

BTW:

1. Old browsers don't support clip-path, [caniuse](https://caniuse.com/#feat=css-clip-path)
2. You should change the width and height at <http://bennettfeely.com/clippy/>, mine is squashed.

**Comment by Edouard-Legoupil** [comment]
Thanks -- Which specific file shall I edit 

I tried to replace this 
https://github.com/laozhu/hugo-nuo/blob/master/assets/styles/partials/_header.scss#L5:L6

 /* border-radius: 50%;
  border: 4px solid $media-border; */

  -webkit-clip-path: polygon(50% 0%, 100% 25%, 100% 75%, 50% 100%, 0% 75%, 0% 25%);
clip-path: polygon(50% 0%, 100% 25%, 100% 75%, 50% 100%, 0% 75%, 0% 25%);

but it did not worked out..  Sorry CSS is not my big strength...

**Comment by laozhu** [comment]
@Edouard-Legoupil  You CSS is OK, It's my fault caused by using PWA cache-first strategy, I have fixed this problem in #101, you can pull the new version and do it again.
