### ISSUE TITLE
可否调整一下header的css

### ISSUE THREAD

**Issue by vozhuo** [laozhu/hugo-nuo#107]
我的笔记本是1366x768的，Social Network显示不出来。

**Comment by laozhu** [comment]
Hi @vozhuo,  I changed min-height from 768px to 720px, now if the screen height < 720px, social network will hidden.

**Comment by vozhuo** [comment]
还是不行，我具体调了一下max-height是656px时可以显示，657px就不显示了。720px时我只有按F11浏览器全屏后才能显示。

**Comment by laozhu** [comment]
@vozhuo 你可以在 `styles/custom.css` 里根据自己需要覆盖默认样式，默认值再改小的话就会和主菜单重合了。

<https://github.com/laozhu/hugo-nuo#custom-theme>
