### ISSUE TITLE
Compiling Sass

### ISSUE THREAD

**Issue by BolajiAyodeji** [laozhu/hugo-nuo#109]
Hello, this is more of a question than an Issue!
What command do I need to run to compile my modified sass to css.
I can't seem to modify styles, it's not rendering.

Does it compile when I run `hugo` or how?
I tried making changes to the `styles/custom.scss` and then ran `hugo` to no avail.

Any suggestions, please?

**Comment by laozhu** [comment]
Hi @BolajiAyodeji, check your hugo version, maybe it's an old one, the hugo version after [v0.43](https://gohugo.io/news/0.43-relnotes/) supported hugo pipes and sass natively.

[Hugo Pipes allows the processing of SASS and SCSS files](https://gohugo.io/hugo-pipes/scss-sass/)

**Comment by BolajiAyodeji** [comment]
I am using the latest version `v0.53`

**Comment by BolajiAyodeji** [comment]
But normally when I run `hugo`, it ought to compile automatically right?
I don't seem to understand

**Comment by laozhu** [comment]
Have you uncommented this line in your `config.toml`?

```toml
# customStyle = "styles/custom.scss"
```

**Comment by BolajiAyodeji** [comment]
No, I just did that and ran `hugo`
I got this error
```
Building sites … ERROR 2019/01/29 15:35:10 error: failed to transform resource:TOCSS: failed to transform "styles/custom.scss" (text/x-scss): this feature is not available in your current Hugo version
Total in 95 ms
Error: Error building site: logged 1 error(s)
```

what is wrong? I have the latest version, I downloaded it from GitHub, `v0.53`

**Comment by BolajiAyodeji** [comment]
See
```
 hugo version
Hugo Static Site Generator v0.53-8FC339DC2529FF77E494A1C12CD1FF9FBCB880A4 windows/amd64 BuildDate: 2018-12-24T08:26:16Z
```

**Comment by laozhu** [comment]
@BolajiAyodeji I know what's the problem, you should download the extended hugo version which contains sass module.

Below is my hugo version:

```bash
~/D/@/my-blog ❯❯❯ hugo version
Hugo Static Site Generator v0.53/extended darwin/amd64 BuildDate: unknown
```

**Comment by laozhu** [comment]
<https://github.com/gohugoio/hugo/releases>

The last one is the extended version.

**Comment by BolajiAyodeji** [comment]
I just did that, it worked!
Thanks a lot

**Comment by BolajiAyodeji** [comment]
I have another issue with images, should I ask here or open a new issue?

**Comment by laozhu** [comment]
@BolajiAyodeji Open another one for discussion.
