### ISSUE TITLE
增加畅言打赏支持

### ISSUE THREAD

**Issue by amosbird** [laozhu/hugo-nuo#11]
https://github.com/tufu9441/maupassant-hexo/pull/301/files

**Comment by laozhu** [comment]
当用户使用畅言作为评论系统时，已增加打赏实验室功能 (8d1904aeb861638548a8da728807ac6918445d18)，支持支付宝和微信打赏，具体配置见畅言官方说明：

<http://changyan.kuaizhan.com/labs/reward>
