### ISSUE TITLE
PWA not adding to home screen

### ISSUE THREAD

**Issue by BolajiAyodeji** [laozhu/hugo-nuo#111]
PWA not adding to home screen, I debugged in Chrome Dev Tools and got this error.
```
Site cannot be installed: no matching service worker detected. You may need to reload the page, or check that the service worker for the current page also controls the start URL from the manifest
```

What could be wrong?
My manifest and service-worker was setup correctly, I can see it up in Dev Tools also

**Comment by laozhu** [comment]
Hi @BolajiAyodeji, I can't figure out your problem based on your error info. I test `adding to home screen` feature with [my blog](https://laozhu.me) in Chrome browser (Mac), it's OK.

BTW, the service-worker.js file is here 👇

[hugo-nuo/assets/service-worker.js](https://github.com/laozhu/hugo-nuo/blob/master/assets/service-worker.js)

**Comment by BolajiAyodeji** [comment]
I've fixed this, thank you!
