### ISSUE TITLE
Add multiple images support

### ISSUE THREAD

**Issue by allenanswerzq** [laozhu/hugo-nuo#113]
I would love to have a feature that can support multiple images showing in the horizontal direction.

Found this [link](http://yoshiharuyamashita.com/post/hugo-shortcode-to-show-multiple-images/) to show the effect what I expected would look like. 

I was trying to add the [Blackburn](https://github.com/yoshiharuyamashita/blackburn) theme's shortcode into hugo-nuo theme, but it didn't work, so sad :-(

**Comment by laozhu** [comment]
Add to todo list, closed.
