### ISSUE TITLE
The links page 按照指南操作报错

### ISSUE THREAD

**Issue by huangsiyu86** [laozhu/hugo-nuo#114]
hi,
感谢你的模板，我在添加 links page 时报错了，错误如下：
![image](https://user-images.githubusercontent.com/28700764/52845798-fa647180-3142-11e9-94b6-1fa8754a3265.png)
经过排查发现是 links.yml 的语法不正确造成的，后来改成如下可以正常使用 links 页面：
![image](https://user-images.githubusercontent.com/28700764/52845872-2849b600-3143-11e9-806e-8c4536ae99c7.png)
不知道这是普遍存在的问题，还是我这边个人操作的问题。

另一个小问题是一处笔误：
![image](https://user-images.githubusercontent.com/28700764/52845977-621abc80-3143-11e9-93ee-35d9d1f3ccbe.png)

**Comment by laozhu** [comment]
@huangsiyu86 感谢反馈，是我的问题。

例子里的语法是 `toml` 语法，但是 `yml` 是 `yaml` 语法的后缀，文档里混在一起了，我等会改下。

```
links.yml => yaml
links.toml => toml
```
