### ISSUE TITLE
如何在custom.scss中覆盖variables.scss的参数

### ISSUE THREAD

**Issue by vozhuo** [laozhu/hugo-nuo#115]
如题

**Comment by laozhu** [comment]
@vozhuo 目前不好做覆盖，只能修改主题中的 [`_variables.scss`](https://github.com/laozhu/hugo-nuo/blob/master/assets/styles/partials/_variables.scss) 文件中的变量。原因如下：

> [`main.scss`](https://github.com/laozhu/hugo-nuo/blob/master/assets/styles/main.scss) 和 [`custom.scss`](https://github.com/laozhu/hugo-nuo/blob/master/assets/styles/custom.scss) 两个文件都使用 [`_variables.scss`](https://github.com/laozhu/hugo-nuo/blob/master/assets/styles/partials/_variables.scss) 中的变量，但不好覆盖变量，因为在其中一个文件修改变量并不会覆盖另一个文件中的变量；如果直接在 [`main.scss`](https://github.com/laozhu/hugo-nuo/blob/master/assets/styles/main.scss) 中导入 [`custom.scss`](https://github.com/laozhu/hugo-nuo/blob/master/assets/styles/custom.scss)，最后编译成一个样式文件，可以在[`custom.scss`](https://github.com/laozhu/hugo-nuo/blob/master/assets/styles/custom.scss) 中覆盖变量，但会失去了 [自定义样式（同时不改主题）](https://github.com/laozhu/hugo-nuo/issues/106) 的初衷。

你有什么好主意的话可以分享下，可行的话我来实现。
