### ISSUE TITLE
CSS highlight problem for linenos=table

### ISSUE THREAD

**Issue by bebound** [laozhu/hugo-nuo#117]
The table width is not 100% when using linenos=table.

<img width="936" alt="Screen Shot 2019-03-10 at 18 47 45" src="https://user-images.githubusercontent.com/2227874/54083922-11266e80-4365-11e9-8ebf-60a340e2fabd.png">

Here is the markdown file. (linenos=inline works as expected)

```
+++
title = "test"
+++


{{< highlight python3 "linenos=table, linenostart=1" >}}
def X1():
    return "x1"
{{< / highlight >}}

{{< highlight python3 "linenos=inline, linenostart=1" >}}
def X1():
    return "x1"
{{< / highlight >}}
```

**Comment by laozhu** [comment]
@bebound I tested with your code, there's some style overrides with my [content.scss](https://github.com/laozhu/hugo-nuo/blob/master/assets/styles/partials/_content.scss#L171) and [table.scss](https://github.com/laozhu/hugo-nuo/blob/master/assets/styles/partials/_table.scss#L2), I will fix it later.

**Comment by bebound** [comment]
There is also a CSS problem only occur on Safari(macOS and iOS).
The code block has space on the right side. 
[url](https://blog.fromkk.com/post/circular-import-in-python/)


![Screen Shot 2019-03-12 at 5 12 42 PM](https://user-images.githubusercontent.com/2227874/54188283-5627dd80-44ea-11e9-9427-679a29f19554.png)
![Screen Shot 2019-03-12 at 5 12 50 PM](https://user-images.githubusercontent.com/2227874/54188290-588a3780-44ea-11e9-9b2c-65fe2bc666ff.png)

**Comment by laozhu** [comment]
@bebound Safari problem is caused by this CSS property.

```css
body {  
  font-feature-settings: "liga" on;
}
```

I will fix the issue tonight.
