### ISSUE TITLE
Changing the favicon

### ISSUE THREAD

**Issue by aaronkjones** [laozhu/hugo-nuo#119]
There are previous discussions talking about doing this, #57 and #16 but they are above my understanding. I am very new to using Hugo. Can someone provide a step by step on how to do it?

Such as...

```
cd themes
git clone https://github.com/laozhu/hugo-nuo
...
```

**Comment by laozhu** [comment]
Hi @aaronkjones, you can reset the avatar link in your `config.toml`, but I think the simplest method is replacing the avatar and icons in the theme with your own images and keep the name the same.

- [avatar and background folder](https://github.com/laozhu/hugo-nuo/tree/master/assets/images)
- [favicon and icons folder](https://github.com/laozhu/hugo-nuo/tree/master/static)

If you want to develop the theme to your own theme, just start from [head.html](https://github.com/laozhu/hugo-nuo/blob/master/layouts/partials/head.html#L3).

**Comment by aaronkjones** [comment]
Can this be done without modifying the theme? The theme is added as a submodule so that I can keep it updated. If I make changes, they will be overridden when I do.

**Comment by laozhu** [comment]
Hi, @aaronkjones 

Copy `themes/hugo-nuo/assets` and `themes/hugo-nuo/static` to your blog root dir and keep the filename the same with theme.

```bash
~/D/@/my-blog ❯❯❯ tree -L 2
.
├── config.toml
├── assets
│   └── images          <-- replace images
├── static
│   ├── favicon.ico     <-- replace favicon.ico
│   ├── icons           <-- replace icons
│   └── manifest.json
└── themes
    └── hugo-nuo
```

Above is your blog repo structure, now you can replace images with your own, and don't need to modify theme anymore.

**Comment by aaronkjones** [comment]
Thanks so much and sorry to resurrect this topic
