### ISSUE TITLE
Media resources

### ISSUE THREAD

**Issue by ghost** [laozhu/hugo-nuo#123]
If I create a new post, is there any way to automatically create the post directory within `./content/media/`to save the post's resources?

**Comment by laozhu** [comment]
I think [directory based archetypes](https://gohugo.io/content-management/archetypes/#directory-based-archetypes) is what you want, maybe you can override the default [archetype/post.md](https://github.com/laozhu/hugo-nuo/blob/master/archetypes/post.md) in your site's archetypes folder.
