### ISSUE TITLE
这是什么原因？

### ISSUE THREAD

**Issue by kxsv** [laozhu/hugo-nuo#124]
error: failed to transform resource: TOCSS: failed to transform "styles/main-rendered.scss" (text/x-scss):

**Comment by laozhu** [comment]
@jincangkang 我这里运行 `hugo server` 和 `hugo` 都是 OK 的，你提供的信息太少了，没法知道什么问题。

**Comment by kxsv** [comment]
操作系统：mac os 10.13.6
hugo版本：v0.55.5

$  hugo server

Building sites … WARN 2019/05/13 02:05:19 Page's .Hugo is deprecated and will be removed in a future release. Use the global hugo function.
ERROR 2019/05/13 02:05:19 error: failed to transform resource: TOCSS: failed to transform "styles/main-rendered.scss" (text/x-scss): this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
Total in 22 ms
Error: Error building site: logged 1 error(s)

**Comment by laozhu** [comment]
@jincangkang You should install `hugo_extended` version to compile SCSS to CSS.
