### ISSUE TITLE
Please make logo rotation optional

### ISSUE THREAD

**Issue by mbrukman** [laozhu/hugo-nuo#127]
Your website logo is the letter "Z" which is great, because after 180° rotation, it still looks like a Z! However, that doesn't work in all cases (most other letters, except I and O perhaps), so having it rotate on mouseover is a bit confusing in majority of other cases.

It would be nice to make this optional (off by default) or at least configurable (if true by default), though it's probably that only a few logos will be able to rotate and still remain meaningful after a rotation.

If this is already possible, I didn't see how to turn it off in the README; it would be nice to document this as well.

**Comment by bebound** [comment]
I second this. How about use `rotate(360deg)` as default value?
