### ISSUE TITLE
Consider clicking logo or title mean "go back to home page"

### ISSUE THREAD

**Issue by mbrukman** [laozhu/hugo-nuo#128]
Looking at a single post, one might imagine that clicking on the logo or the website name would take you back to the home page, but that is not the case — neither of them is clickable.

It would be nice to make clicking either of them return back to the home page; that seems to be a common pattern I've seen which makes it easy to return to the home page, without having to manually use the back button in the browser, or having to open the navigation menu (at the top on mobile, since neither logo not website name are clickable) to find the "Home" link.

**Comment by laozhu** [comment]
Hi, @mbrukman 

I will deal with your issues in the next several days, thank you for your feedback.
