### ISSUE TITLE
Make it more obvious how to change favicon

### ISSUE THREAD

**Issue by RAOF** [laozhu/hugo-nuo#16]
Hi there! Thanks for the really neat theme.

I'm having trouble overriding the default favicon; I've got `static/img/favicon.ico`, `static/img/favicon-32x32.png` and `static/img/favicon-16x16.png` to override the default images, but I still see the default "Z" favicon.

What extra files do I need to override to change the favicon? (I'll submit a pull request updating the documentation once I know how to do it 😄 )

**Comment by laozhu** [comment]
If you don't want develop & generate static files from src, just replace images in folder `static/img` indicated in below screenshot and force-refresh your browser (maybe cached).

![image](https://user-images.githubusercontent.com/1212457/30415750-091410a8-995c-11e7-9214-5c8e6e0f2b33.png)

If you want develop & generate static files from src, you should replace images in folder `src/images`, the structure and filenames are the same with `static/img`, when you change images in `src/images` folder, do copy & replace with `npm install && npm run images` command.

![image](https://user-images.githubusercontent.com/1212457/30416164-b9a54666-995d-11e7-81f2-a0129810d2f8.png)

`package.json ↑`

I generate these favicon and touch icons with [realfavicongenerator](https://realfavicongenerator.net/).

**Keep the generated images' filename the same with the theme's.**

**Comment by RAOF** [comment]
Thanks, I think that worked.

I owe you a PR to update the readme 😀

**Comment by laozhu** [comment]
I will wait for it forever 😂

**Comment by laozhu** [comment]
Solved in #119
