### ISSUE TITLE
Disqus 评论不见了

### ISSUE THREAD

**Issue by bwangelme** [laozhu/hugo-nuo#17]
@laozhu 你好，这两天我在更新了主题之后，发现我配置的disqus评论不见了，我的hugo项目的配置文件`config.toml`中已经添加了配置语句`disqusShortname = "bwangel"`，我想应该不是因为配置的原因。

我在代码中看到，disqus是在[single.html](https://github.com/laozhu/hugo-nuo/blob/master/layouts/post/single.html#L33-L34)中引入的，它加载了一个`_internal/disqus.html`的模板，但是我在整个项目中并没有找到这个文件，所以想问一下，这个文件是不是被误删了？

**Comment by laozhu** [comment]
@bwangel23 我测试了下，还在的，这个 disqus 模板不是我写得，是 hugo 自带的。

<https://gohugo.io/templates/internal/#disqus>

**Comment by bwangelme** [comment]
找到问题了，我的配置文件中：
```
[permalinks]
  post = "/:year/:month/:day/:title/"
```
放到了`disqusShortname = "disqus_shortname"`的前面，结果导致`.Site.DisqusShortname`为空。

谢谢 @laozhu，已经解决了。
