### ISSUE TITLE
代码高亮如何设置?

### ISSUE THREAD

**Issue by peach5460** [laozhu/hugo-nuo#18]
我是用示例中的代码,放到我的文本里,生成的html并没有着色
```javascript
// Initialize video.js player
if (document.getElementById('my-player') !== null) {
  /* eslint-disable no-undef */
  videojs('#my-player', {
    aspectRatio: '16:9',
    fluid: true,
  });
}
```

**Comment by laozhu** [comment]
@peach5460 Hugo 0.28 之前的版本需要安装 [Pygments](http://pygments.org/) 这个 Python 语法高亮包，之后的版本替换成 Golang 内建的包了，不再需要 Pygments，先检查一下你的 Hugo 版本吧。

详细的介绍看：[Hugo 官方的文档](https://gohugo.io/content-management/syntax-highlighting/)

**Comment by peach5460** [comment]
我是0.29版,但是生成的html页面并没有着色

---
好吧,我知道了
把pygmentsuseclasses = true去掉就行了

打扰了
