### ISSUE TITLE
Need an option to disable MathJax

### ISSUE THREAD

**Issue by deepjia** [laozhu/hugo-nuo#19]
Have got some parentheses in articles, which are auto converted by MathJax. Need an option to disable that. Example: TextA(TextB)

文章中有一些小括号包裹的普通文本，被 MathJax 自动转换了样式。希望能够有关闭它的入口。形如：TextA(TextB)

**Comment by laozhu** [comment]
这个可能是因为我修改了 MathJax 的默认标签导致的，你看下 `footer` 模版里的：[这几行代码](https://github.com/laozhu/hugo-nuo/blob/26e83c246b02efef5d5369fd5bd836a99ab11e94/layouts/partials/footer.html#L13)

现在主题中的行内公式支持“美元”和“括号”两种标签形式，如果冲突你可以把“括号”形式去掉或改成其他的形式就不冲突了。

```html
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  tex2jax: {
    inlineMath: [['$','$']],
    displayMath: [['$$','$$']],
});
</script>
```

但是美元 `$...$` 和 `$$...$$` 也可能遇到冲突的问题，详见 #10 的解释，你可以设置一个超级复杂的标签标记公式，这样就永远不会冲突啦😄

**Comment by deepjia** [comment]
原来在 footer 里，我改成美元加括号了，已搞定，多谢🙏
