### ISSUE TITLE
encoding of bundle.css

### ISSUE THREAD

**Issue by kohleth** [laozhu/hugo-nuo#21]
Hi,

first of all, I think hugo-nuo looks very nice. Thanks for publishing it.

A question. What encoding is bundle.css (esp. the iconfont scripts) in?
I would like to modify some part of the css, such as not rotating my avatar on hover(since it is not a Z), but everytime I open bundle.css, it messes up the encoding, so when I save it with my edits many other things fail, such as the iconfonts (github, email, menu etc...).

**Comment by laozhu** [comment]
Hi, bundle.css is a generated file by sass, you shouldn't edit it directly. If you just want to replace the Z logo with yours, replace image files in the `static/img` folder and keep their names in place.

If you want to build styles totally by yourself, you should install [sass](http://sass-lang.com/) then run commands below in the terminal.

```bash
cd themes/hugo-nuo
sass --scss --style compressed --watch ./src/styles/main.scss:./static/css/bundle.css
```

Now you can change styles `.scss` files in the `src/styles` folder.

**Comment by kohleth** [comment]
that is helpful to know. Thanks.

**Comment by kohleth** [comment]
On a related note, how should I modify the index.js / bundle.js files?

**Comment by laozhu** [comment]
You should run `npm install` to install all devDependencies, then you can build everything from source.

[Visit this section for details.](https://github.com/laozhu/hugo-nuo#build)
