### ISSUE TITLE
能否在PC端显示footer？

### ISSUE THREAD

**Issue by 40huo** [laozhu/hugo-nuo#22]
有些托管的地方可能需要在首页加点什么内容，比如coding.net就需要加上Hosted on Coding.net才能不跳转，我加在footer里但是只有移动端才能看得到。
可否在PC端也加上footer的显示？
另外，是否可以在配置里增加这么一项内容，可以让用户添加一些托管商的标志，比如七牛的图片广告之类的。

**Comment by ericpai** [comment]
确实有需要显示 footer 的需求，可否在 config.toml 里加一个配置项控制是否显示footer

**Comment by laozhu** [comment]
PC端主要是没想到特别好的展现方式，加在列表页（有分页的情况下）不好看。

**Comment by SylarMa** [comment]
需要footer在pc端显示
