### ISSUE TITLE
<a>标签的长度超过post-content

### ISSUE THREAD

**Issue by abcdsxg** [laozhu/hugo-nuo#24]
![_013](https://user-images.githubusercontent.com/20315934/31582578-13ffcab8-b1ba-11e7-974c-01d14e5e129b.png)
如果<a>标签的文本很长时，会突破post-content的长度

**Comment by abcdsxg** [comment]
还有个问题，pull了最新的代码后，代码高亮出问题了。。
![_014](https://user-images.githubusercontent.com/20315934/31582591-b84856e4-b1ba-11e7-9705-e46af7e197a8.png)

**Comment by laozhu** [comment]
@abcdsxg 代码高亮无效的话可能你要升级下 hugo 的版本。

>From Hugo 0.28, the default syntax hightlighter in Hugo is Chroma; it is built in Go and is really, really fast – and for the most important parts compatible with Pygments.

<https://gohugo.io/content-management/syntax-highlighting/>

**Comment by laozhu** [comment]
@abcdsxg  确实存在问题，谢谢指出，已经修复了 1cbde7258a49876e33afcc6e37e0dbe6ad5c789c

通常来说不会使用 `break-all`，因为会影响英文文章的可读性，会使用 `break-word` 在英文单词结束处断开，如果这个单词超级长（甚至超过一行）再强行断开单词换行。

虽然这是个 bug，还是建议你文章中长的链接使用 `[link-title](http://long-link-url)` 格式，而 inline code 本身其实也不适合太长的文字。

**Comment by abcdsxg** [comment]
感谢，已经更新版本，问题都解决了
