### ISSUE TITLE
Theme uses "post" instead of "posts"

### ISSUE THREAD

**Issue by dialupdisaster** [laozhu/hugo-nuo#25]
The hugo documentation and all other themes use the archetype of "posts" instead of "post" so this theme diverges from them. Is there anyway it can be corrected in the repo?

I corrected my local copy but I am sure it is confusing for others to try and use when [following the documentation](https://gohugo.io/getting-started/quick-start/) works until you try to use this theme.

**Comment by laozhu** [comment]
Hi, @digitalfiz thank you for this advice.

But this is not a mistake, I prefer singular [/post/cjk-webfont-usage](https://laozhu.me/post/cjk-webfont-usage/) than plural in post URL.

And there are several sites using hugo-nuo theme now, if I change to plural, their post URL will be broken.
