### ISSUE TITLE
HTML escaped in Summary

### ISSUE THREAD

**Issue by laozhu** [laozhu/hugo-nuo#3]
![HTML unescaped in summery](https://user-images.githubusercontent.com/1212457/28931688-6f69b106-78a9-11e7-8bdc-eac03cf50131.png)

Some characters like `rsquo;` appeared in post summery.

**Comment by bep** [comment]
See https://github.com/laozhu/hugo-nuo/blob/master/layouts/post/summary.html#L9

Using `plainify` is probably a mistake here.

**Comment by laozhu** [comment]
@bep Thanks for report my mistake.

I replaced with `{{ .Summary | plainify | htmlUnescape }}` that seems OK.

![HTML unescaped in Summary](https://user-images.githubusercontent.com/1212457/28932249-698c9292-78ab-11e7-86c7-1d62df1da70e.png)

**Comment by bep** [comment]
>I replaced with {{ .Summary | plainify | htmlUnescape }} that seems OK.

For `.Summary` that seems like overkill; it should already be `plain` and ready to go. If the user used the summary delimiter it may contain formatting, but that is probably what the user wanted.

**Comment by laozhu** [comment]
@bep Thanks for your reply, maybe its overkill but that's what I want keep :)

I create this theme with clean post list view, there's only two type of entry layout:

- Item with cover
- Item without cover

If there's html tags in summery, the style maybe unpredictable and the post list will not clean.

**Comment by hellt** [comment]
But still, if there will be markdown syntax like **bold** or `code`, will it render on the main page?

**Comment by laozhu** [comment]
Hello, @hellt I also think keep the summery with inline styles is better, but I didn't find function in hugo which can remove tags except inline `strong`, `em`, `code` ones.
