### ISSUE TITLE
Syntax highlighting for R not working

### ISSUE THREAD

**Issue by lch14forever** [laozhu/hugo-nuo#32]
Hi,

Thanks for the great theme!

I found the syntax highlighting not working well for R code.

Following the [instructions](https://bookdown.org/yihui/blogdown/templates.html) ("Enable syntax highlighting via highlight.js" section) fixed the problem.

Chenhao

**Comment by thedevsaddam** [comment]
This is a great theme, I am using it. Yes, syntax highlighting does not work in my case too.

**Comment by laozhu** [comment]
```toml
# pygmentsuseclasses = true
PygmentsCodeFences = true
```

Related to closed issue #18, remove `pygmentsuseclasses` line  in your `config.toml` and have a try.
