### ISSUE TITLE
Need a Tags page

### ISSUE THREAD

**Issue by thedevsaddam** [laozhu/hugo-nuo#33]
I'm using this theme and it's really a good theme. Could you please add a ***Tags*** link to a page, so that all the available tags show on that page

**Comment by laozhu** [comment]
I will make an archive page with tags cloud when I have time :)

**Comment by bwangelme** [comment]
@laozhu 

Hello, I have implemented the __Tags__ in my blog. You can see the it on my blog. [clieck here](https://www.bwangel.me/tags/)

But I'm not master to the web front and design. Can you accept the appearance of my __Tags__ page. If you feel it looks okay, I can make a PR for this issue.

**Comment by laozhu** [comment]
@bwangel23 It's Nice, I need your PR 👍 

你可以先提个 PR，合并后我再稍稍处理下，让他跟整个主题更协调些，我们可以合作把这个功能做掉 :)

**Comment by bwangelme** [comment]
See the PR #35

**Comment by laozhu** [comment]
I have redesigned the tags page referring to the below picture.
@bwangel23 Thanks for your PR, save me lots of time :)

![image](https://user-images.githubusercontent.com/1212457/33330638-575125ca-d49a-11e7-99e8-b49aab0da0c1.png)
