### ISSUE TITLE
使用插件

### ISSUE THREAD

**Issue by Dehong1** [laozhu/hugo-nuo#34]
请问怎么插入音频，与视频，能不能详细介绍一下？谢谢了

**Comment by laozhu** [comment]
你可以使用 HTML5 的 Video 或者 Audio 标签直接插入视频或音频到文章的 Markdown 文件里面，也可以使用 [Hugo Shortcodes](https://gohugo.io/content-management/shortcodes/) 自己封装一下，不管是本地视频还是 YouTube 视频还是其他视频/音频网站的都可以封装，Hugo 官方支持的只有 YouTube 和 Vimeo 两个，本地视频我使用的是 [Video.js](https://github.com/videojs) 播放器封装的，你也可以参考下，用法详见 [这个链接](https://github.com/laozhu/hugo-nuo/blob/master/layouts/shortcodes/video.html)。

国内的视频网站但凡支持 iframe 分享代码的，直接复制到 Markdown 文件或者封装成 Shortcodes 使用都可以的，你可以参考我的 shortcodes 格式自己试试。

**Comment by Dehong1** [comment]
好的，谢谢了
