### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by YonghuiDong** [laozhu/hugo-nuo#43]
很清新的模版，赞！

提一个小建议：主页显示的是每篇博文的第一段。要是一篇博文的第一段写得太长了，就显得很不好看。建议可以加一个summary参数。在主页只显示summary内容。或者按字数限制来显示。

**Comment by YonghuiDong** [comment]
明白了，只要加下面的语句就可以。不过问一下，还是可以支持下summary参数吗？

**Comment by laozhu** [comment]
可以在 markdown 文件用这个分割来控制的。

```html
<!-- more-->
```

就像这样：

![image](https://user-images.githubusercontent.com/1212457/34326822-e0c95d9e-e8f0-11e7-8705-142e84a1e551.png)
