### ISSUE TITLE
  停止avatar旋转

### ISSUE THREAD

**Issue by YonghuiDong** [laozhu/hugo-nuo#45]
我在header.scss里把原来的

> &:hover {
    transform: rotate(180degree);
  }

换成了
> &:hover {
    transform: scale(1.2);
  }

但没有任何相应。我试着改了一些别的参数，也没有响应。请帮忙看一下。谢谢。

**Comment by laozhu** [comment]
我在 Chrome 里面测试一下是可以的。

![image](https://user-images.githubusercontent.com/1212457/34439679-96333464-ecea-11e7-8b49-e65a9fc36b89.png)

效果如下：

![kapture 2017-12-29 at 22 54 45](https://user-images.githubusercontent.com/1212457/34439786-702b4a30-eceb-11e7-809d-4a114637d714.gif)

你修改之后有没有运行 [sass](https://github.com/laozhu/hugo-nuo/blob/master/package.json#L9) 命令重新生成 [static](https://github.com/laozhu/hugo-nuo/tree/master/static) 文件夹下面的静态资源？

**Comment by YonghuiDong** [comment]
@laozhu 谢谢解答，那可能就是没有重新生成static文件夹下静态资源的原因吧。

我是用 blogdown 安装，运行你的模版的。你的模版稍微和别的Hugo模版有些不同。以前尝试的模版在我安装时候在文件夹里会自动额外生成一个 static 文件夹 （非模版文件夹里的static）。每次改完模版，重新 serive site 一下就会更新模版。

结构如下：


├── README.md
├── config.yaml
├── content
├── index.Rmd
├── layouts
│   ├── _default
│   └── partials
├── static
│   ├── CNAME
│   ├── css
│   ├── fonts
│   ├── images
│   ├── js
├── themes
│   └── hugo-lithium-theme
└── website.Rproj

而安装完你的模版后，结构里没有 static 和 layouts 这两个文件夹。 手动复制了这两个文件夹，好像也没反应。

不过你的模版速度要快很多了。所以别的小东西也无关紧要了。

**Comment by laozhu** [comment]
没试过 blogdown 这个工具，也许是静态资源构建方式有所不同吧。
