### ISSUE TITLE
能否在配置中更改配色？

### ISSUE THREAD

**Issue by 40huo** [laozhu/hugo-nuo#46]
RT
有时候头像是红色系的，配绿色的链接颜色什么的有点违和，希望能在配置中增加一项，选RGP值之类的。

**Comment by laozhu** [comment]
@40huo 这个操作是可以的，但不是在配置里做，是在样式源文件 [variables.scss
](https://github.com/laozhu/hugo-nuo/blob/master/src/styles/partials/variables.scss#L33) 中修改主题颜色，然后重新构建生成目标样式。

**Comment by ShaneTian** [comment]
为什么现在变成了这样
![image](https://user-images.githubusercontent.com/42370681/45941986-2572eb00-c013-11e8-8658-05e9fa65b73c.png)
我自己用这个主题也是这样……
