### ISSUE TITLE
我想更改壁纸改完这个值怎么不生效

### ISSUE THREAD

**Issue by kuops** [laozhu/hugo-nuo#48]
改的`variables.scss` 这个文件中的
```
$background-image: url('../img/grey-prism.svg');
```
直接写到这个文件也不行 `skeleton.scss`

**Comment by laozhu** [comment]
1. 如果你的图片文件放在 `src/images` 目录下，运行 npm 命令把图片 copy 到 static/img 目录下

```bash
# yarn or npm
$ yarn images
$ npm run images
```

2. 所有的样式修改，都要运行 sass 命令行重新 build 成 css 文件

```bash
# yarn or npm
$ yarn sass
$ npm run sass
```
