### ISSUE TITLE
代码注释有一些bug

### ISSUE THREAD

**Issue by ZhyCong** [laozhu/hugo-nuo#49]
1. 注释颜色异常

![image](https://user-images.githubusercontent.com/23568935/34918122-32f871f6-f989-11e7-956e-08de9cd19acf.png)

2. \```js ```格式的注释, 有时被转为纯文字
3. 使用// 单行注释会导致代码块失效

**Comment by laozhu** [comment]
这个问题确实存在，我刚才也复现了，但是应该不是主题的问题，我也去提了个 [issue](https://github.com/gohugoio/hugo/issues/4314) 等回复吧。

**Comment by laozhu** [comment]
已经修复 https://github.com/alecthomas/chroma/issues/106
