### ISSUE TITLE
我们不一样？

### ISSUE THREAD

**Issue by edsion1107** [laozhu/hugo-nuo#50]
![2018-01-16 11 22 46](https://user-images.githubusercontent.com/1925286/34970520-b5c8efc6-faaf-11e7-8cb2-1077102e2a3f.png)
![2018-01-16 11 22 59](https://user-images.githubusercontent.com/1925286/34970521-b6203420-faaf-11e7-911b-e2a563d1c3f1.png)
为什么我这插入的代码是没有背景和高亮的？
第一张图是你博客的，第二张图是我把`themes/hugo-nuo/exampleSite/content/post/hugo-nuo-post-preview.md`拷贝到了`content/post/hugo-nuo-post-preview.md`以后的效果

**Comment by laozhu** [comment]
1. 你看下配置文件 [config.toml](https://github.com/laozhu/my-blog/blob/master/config.toml) 是不是有点不一样。 配置的选项可以参考 [官网](https://gohugo.io/content-management/syntax-highlighting/#configure-syntax-hightlighter)

2. 如果你使用了 `pygmentsUseClasses=true`，还需要生成一个配色方案，参考 [这里](https://gohugo.io/content-management/syntax-highlighting/#generate-syntax-highlighter-css)

**Comment by edsion1107** [comment]
明白了
