### ISSUE TITLE
麻烦适配jekyll theme和设置分享插件

### ISSUE THREAD

**Issue by smileklvens** [laozhu/hugo-nuo#52]
麻烦适配jekyll theme和设置分享插件，多谢了

**Comment by laozhu** [comment]
不好意思，最近暂时还没有时间整这个
兄弟切换到 [hugo](http://gohugo.io/) 吧，性能和功能上都要强于 jekyll 的，开发者社区也很活跃 😂

[Hugo vs. Hexo vs. Jekyll](https://stackshare.io/stackups/hexo-vs-hugo-vs-jekyll)
