### ISSUE TITLE
如何换favicon

### ISSUE THREAD

**Issue by sfdye** [laozhu/hugo-nuo#57]
有什么好的办法吗？

**Comment by wenbo5565** [comment]
I have the same question to change favicon. I use blogdown and have tried several ways but haven't made it yet. Please let me know how I can change to a new favicon. Thank you.

**Comment by sfdye** [comment]
@laozhu

**Comment by Tuanz1** [comment]
修改image下的文件，然后执行npm run image 应该就可以了

**Comment by sfdye** [comment]
@Tuanz1 npm??? 这不是hugo吗

**Comment by Tuanz1** [comment]
用的hugo框架来构建的整个网站的文件，但是缩略图什么是用npm 里面的　image 生成

**Comment by Tuanz1** [comment]
@sfdye 你可以看他项目的readme 关于build的这一部分

**Comment by sfdye** [comment]
@Tuanz1 谢谢 我明白了

看了下作者源代码：
https://github.com/laozhu/hugo-nuo/blob/master/layouts/partials/head.html#L85-L90

根本原因是favicon现在是hardcode成默认的，而我希望能在`config.toml`里面自定义这个参数。只需要在header.html里面用`{{ .Site.Params.favicon }}`然后提供一个默认值就好了。我有空做一个PR。

**Comment by Tuanz1** [comment]
@sfdye 你有尝试修改content.scss里面的样式么？自定义content.scss里面的内容，但是npm run sass 后还是没有变化是什么原因么

**Comment by sfdye** [comment]
@Tuanz1 我用的是submodule安装这个theme，所有就不能用npm了，毕竟我不想修改原repo，只想通过修改config。按我刚才说的方法修改`head.toml`，已经可以用了。

**Comment by tomriddle1234** [comment]
作者用的favicon包含Android和Apple的各种版本，你需要在自己的static 目录下也制作相应的文件。或者在theme目录的static文件夹下，删除自带的各种favicon

**Comment by wenbo5565** [comment]
@sfdye Hi, 我对hugo以及网页相关的概念不熟悉。请问可不可以详细说一下如何改head.toml?谢谢。

**Comment by laozhu** [comment]
不使用 Webpack 构建，直接替换 static 目录下的 favicon.ico 就可以了
使用 Webpack 构建的话，替换 [src/assets](https://github.com/laozhu/hugo-nuo/tree/master/src/assets) 目录下的 favicon.ico 然后运行 yarn build 会自动 Copy 到 static 目录下。

**Comment by sfdye** [comment]
@laozhu 还是没有解决啊，我用的submodule直接依赖你这个repo，所以我无法直接修改favicon。

```bash
git submodule add https://github.com/laozhu/hugo-nuo themes/hugo-nuo
```

https://sfdye.com/post/migrate-from-jekyll-to-hugo/

**Comment by laozhu** [comment]
@sfdye 明白了，你是希望在 `config.toml` 里面可以修改 favicon.ico 和其他图标，不想修改主题。我正在用 hugo pipelines 替代 npm 和 webpack 这套，我会把一些原来硬编码的配置移到 `config.toml` 里面的。

**Comment by sfdye** [comment]
赞！等你更新

**Comment by wenbo5565** [comment]
感谢

**Comment by laozhu** [comment]
Solved in #119
