### ISSUE TITLE
Could not find an option named "scss".

### ISSUE THREAD

**Issue by madneal** [laozhu/hugo-nuo#62]
运行 npm run sass
```
> hugo-nuo@1.0.0 sass C:\Users\neal1\project\hugo-nuo
> sass --scss --style compressed --watch ./src/styles/main.scss:./static/css/bundle.css

Could not find an option named "scss".`
```
sass npm包和 gem 包都安装了，系统是 win10

**Comment by madneal** [comment]
还有就是想问你的 .eslintrc .stylintrc 上传了么 构建一堆报错

**Comment by wildpan** [comment]
@neal1991 我也是同样的报错，估计是eslint 和 stylelint 的格式不对，或者是代码被其他编辑器给格式化了吧。

**Comment by laozhu** [comment]
现在的版本使用 Webpack 构建静态资源，请按照 [构建帮助](https://github.com/laozhu/hugo-nuo#build) 的说明搭建环境。

备注：我正在重构这个主题，下个版本会移除 Webpack 直接使用 [Hugo Pipelines](https://gohugo.io/hugo-pipes/) 构建静态资源。

**Comment by laozhu** [comment]
@neal1991 @wildpan 当前版本的 eslint 和 stylelint 配置文件均写在 [package.json](https://github.com/laozhu/hugo-nuo/blob/master/package.json#L57) 里面，无需单独的配置文件，但需要安装 package.json 中的依赖包。
