### ISSUE TITLE
老朱你好，来看下我代码css的问题

### ISSUE THREAD

**Issue by jellynian** [laozhu/hugo-nuo#63]
<img width="1329" alt="wx20180321-195259 2x" src="https://user-images.githubusercontent.com/29446726/37708470-c1edf778-2d41-11e8-8609-5fb124fa8730.png">
我的代码css没有颜色。直接克隆你的主题，不知道为什么能帮忙看下吗

**Comment by wildpan** [comment]
你就这样截图什么都没有？

**Comment by g1mi** [comment]
人家是做开源，又不是做免费公益服务。
issue是用来提出软件当中存在的bug或提出新的feature，你这样这开issue问你自己的问题，试问谷歌度娘颜面何存？

**Comment by jellynian** [comment]
@g1mi  很久以前的东西了，现在用自己写的主题了。
