### ISSUE TITLE
highlight.js

### ISSUE THREAD

**Issue by jimr1603** [laozhu/hugo-nuo#65]
The theme is really nice, but I'd like to add highlight.js code highlighting. https://highlightjs.org/
Is this something you'd consider adding to the theme, or letting me know how to add it?

**Comment by laozhu** [comment]
I use webpack to bundle required packages, If you want to import a new package, you should install [highlightjs](https://www.npmjs.com/package/highlightjs) as dependencies, then you can write some javascript code in [src/index.js](https://github.com/laozhu/hugo-nuo/blob/master/src/index.js) file, finally build your new production `bundle.js` file.

PS: I am rewriting this theme and will replace webpack workflow with Hugo pipelines, in the new version, I will add optional hightlight.js support for you.
