### ISSUE TITLE
Chrome Ad block plugin will block social icons Chrome反广告插件屏蔽社交图标栏

### ISSUE THREAD

**Issue by tomriddle1234** [laozhu/hugo-nuo#67]
Hi,
Thanks for such nice template.
I'm using Adblock Plus plugin in Chrome, and it blocks your template's social icons.
I don't see such problem in Edge .
Cheers.

**Comment by laozhu** [comment]
I use social icons and adblock togerther.
It's Okay on [my blog](https://laozhu.me)
