### ISSUE TITLE
'pager size' must be a positive integer

### ISSUE THREAD

**Issue by runo280** [laozhu/hugo-nuo#7]
I added theme to my blog, after that created a post and run this command: `hugo server -D`, but I got empty page in browser, also `hugo` command gives this error:

`Started building sites ...
ERROR 2017/08/17 13:50:25 Error while rendering "home": template: ~/blog/quickstart/themes/hugo-nuo/layouts/index.html:7:21: executing "main" at <.Paginate>: error calling Paginate: 'pager size' must be a positive integer`

I'v tested `ananke` theme, there was no error and blog came up.
Ubutnu 16.04, Hugo 0.26

**Comment by laozhu** [comment]
If you didn't set `paginate` in the `config.toml` file

```toml
[params]
  paginate = 10
```

Maybe you will get this error, It is still my fault, I didn't set default value for paginate. I set a value (10) now you can have a try.

**Comment by runo280** [comment]
Solved, thanks.
