### ISSUE TITLE
找不到js/bundle.js css/bundle.css

### ISSUE THREAD

**Issue by chanjarster** [laozhu/hugo-nuo#79]
浏览器页面渲染有问题，发现找不到`js/bundle.js`，然后发现theme里的js文件名是`./themes/hugo-nuo/static/js/bundle.2b14fb9283.js`，名字对不上。

也找不到`css/bundle.css`，theme里没有这个文件。

**Comment by chanjarster** [comment]
原来要build

**Comment by laozhu** [comment]
@chanjarster 目前基于 Webpack，如果你自己修改静态文件，就要 build 了。下个版本会移除 Webpack 构建这一套，用 Hugo 自带的 Hugo Pipe。
