### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by if2O12** [laozhu/hugo-nuo#80]
laozhu，你好，我很喜欢hugo，觉得用它搭建博客快速又轻巧，而通过hugo我找到了你这个主题，说实话很喜欢（通过手机第一次访问），但是觉得还有一点点改进的空间，所以就提了以下一些建议，因为我对网站一些方面的知识很匮乏，所以只是一些使用上的痛点通过文字表述出个人的一点想法。
1. 建议做一个图片弹出的窗口就是点击图片弹出预览窗口，可参考[这个](http://www.codesheep.cn/2018/08/09/Redis%E5%AD%97%E7%AC%A6%E4%B8%B2%E7%B1%BB%E5%9E%8B%E5%86%85%E9%83%A8%E7%BC%96%E7%A0%81%E5%89%96%E6%9E%90/)或者[这个更简单点的](https://www.cizel.cn/post/next-one/)。
2. 改进table（这个一定得加框，不然看起来怪怪的），可参考[这个样式](https://tianqi.name/jekyll-TeXt-theme/post/2016/06/10/tables.html)，这样有长行文字的时候手机上访问table也有左右滚动条（可通过手机访问预览效果）。
3. 增加分类，可参考[这个](https://www.wmathor.com/index.php/categories.html)，点击顶部的分类名字可跳转到相应地方，增加分类条目的数目。
4. 增加时间线功能的归档。
5. 文章尾部增加导航和脚注，这位老兄已经提过[issue](https://github.com/laozhu/hugo-nuo/issues/15)了。
6. 至于标签云没太多的需求，目前的就行。
7. 建议左侧边栏调整至顶部，加一个类似下面的右侧边栏，用于展示搜索框，links，about，通告等内容。
![snipaste_20180824_141950](https://user-images.githubusercontent.com/42573500/44569036-a6885980-a7ab-11e8-9ab4-58bb7e94bf25.jpg)

**Comment by laozhu** [comment]
哈哈，感谢你提了好多改进意见和新的 feature，我尽量改进。

第一个肯定可以满足，我比较喜欢 Medium 的图片预览风格，会集成这个 [Medium Zoom](https://medium-zoom.francoischalifour.com/) 这个项目。

第二条表格会进行优化。

第四条加上文章归档也可以满足，会有一个专门的文章按时间归档的页面。

第七条这个对这个主题改动太大了，与其这样我还不如重新做个呢 😂，不过我会考虑在右侧增加第三栏，用于展示一些次要信息，比如在文章页面展示文章内目录 TOC

**Comment by if2O12** [comment]
@laozhu 要是这样的话，左侧边栏建议做成可以自动隐藏的。或者优化下能更好的融入整个网页。
