### ISSUE TITLE
缺少bundle.js  bundle.css  cover.jpg 三个文件

### ISSUE THREAD

**Issue by RickieL** [laozhu/hugo-nuo#83]
打开首页提示缺少bundle.js  bundle.css  cover.jpg 三个文件
页面完全乱码了。

我看你在 .gitignore 里把这两个文件给过滤了，那我们怎么使用你这个主题呢。。。

**Comment by BruceEckel** [comment]
This theme seems to be missing a number of components. I had to switch to a different theme.

**Comment by RickieL** [comment]
I use the theme  "hyde-y" now
