### ISSUE TITLE
CSS not showing up in theme

### ISSUE THREAD

**Issue by angela-li** [laozhu/hugo-nuo#85]
Not sure what's happening, but the CSS doesn't look like it's working in this [demo](https://themes.gohugo.io/theme/hugo-nuo/). I downloaded the theme and tried to use it with Hugo, but I ran into the same issue of the styling not showing up.

Would appreciate any help you could provide on this!

**Comment by laozhu** [comment]
@angela-li I merged the latest PR (#78) for using hugo pipe to replace webpack, maybe the merged version is what you need.
