### ISSUE TITLE
Your theme's demo is not working on the Hugo Themes website

### ISSUE THREAD

**Issue by onedrawingperday** [laozhu/hugo-nuo#88]
Hello @laozhu 

I see that since commit 26d0efa your theme is using Hugo Pipes.

However you have not committed the generated resources of your theme and as a result your theme's demo [fails to generate on the Hugo website](https://themes.gohugo.io/hugo-nuo/).

To fix this issue please have a look at the updated README of Hugo Themes: https://github.com/gohugoio/hugoThemes#resources You need to commit the `/resources/` directory and its contents in your theme's repository.

If you have any questions do not hesitate to ask me or @digitalcraftsman

**Comment by laozhu** [comment]
@onedrawingperday Demo fixed.

**Comment by onedrawingperday** [comment]
@laozhu Thank you. I confirm that the demo is now generated with the Themes Site Build Script. 

However the theme's Hugo Pipes Assets are not loading. 

To fix this issue please see the [Common Permalink Issues](https://github.com/gohugoio/hugoThemes#common-permalink-issues) in the Hugo Themes README.

>If you are using Hugo Pipes to publish your theme's resources you need to use `.RelPermalink` in the templates, so that these assets are served correctly on the website.

For example change line 104 of `layouts/partials/` to:
`<link rel="stylesheet" href="{{ $style.RelPermalink }}">`

**Comment by laozhu** [comment]
@onedrawingperday Demo fixed again with commit d2396208fcefc0c37a632a9a9627677c126cd2aa

**Comment by onedrawingperday** [comment]
@laozhu  

I confirm that now your theme's demo is generated when I execute the Build Script.

This will be reflected on the Hugo website the next time themes are updated.

Thanks.
