### ISSUE TITLE
File failed to load: /extensions/MathZoom.js

### ISSUE THREAD

**Issue by riveryc** [laozhu/hugo-nuo#90]
Hi, 不知道这个是不是正常现象, 在 load 好页面后, 点进去某个 post 中, 左下角会提示类似这样的 error:
File failed to load: /extensions/MathZoom.js

不太知道怎么去做进一步的 debug...

**Comment by riveryc** [comment]
Developper mode in Chrome -> Console:
![image](https://user-images.githubusercontent.com/12391265/48449848-049b6a80-e7f8-11e8-91e3-cfb3f05687c7.png)

Thanks!

**Comment by laozhu** [comment]
@riveryc 我看这也有这个报错，可以考虑先把 MathJax 禁用掉，暂时我还没找到解决方案。

**Comment by bwangelme** [comment]
@riveryc 我把 MathJax 的源换成了官方文档上写的 CF 源，这个问题就没了。

```js
<script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML' async></script>
```

+ [官方文档](https://www.mathjax.org/#gettingstarted)

**Comment by laozhu** [comment]
@bwangelme 好像是这样，修好了 👍
