### ISSUE TITLE
postcss 的问题... 

### ISSUE THREAD

**Issue by riveryc** [laozhu/hugo-nuo#91]
又是我, 最近玩 hugo 和你的主题上瘾了~ 哈哈... 再加上我是 DevOps, 所以开始玩上 CICD 了.

我在你的主题的基础上更改了两个 css 文件:
_header.scss
_content.scss
放进了assets/styles 里面

我做了个 Docker Container, 里面集成了hugo, nodejs, npm, postcss-cli.
按说应该是可以 build hugo site 的.
但是我发现了一个问题, 就是每次我用Container build 的时候, resource folder里只生成js 文件夹, 不生成scss 文件夹.
如果用本机( Mac ) 做 build 的时候就有 scss 文件夹了, 从而能继承我的修改. 如果我没猜错, 这个应该是靠 postcss 来生成的吧?

我在Container 里做 `npm install -g postcss-cli` 的时候, 它有个提示:
```
/hugo # npm install -g postcss-cli
/usr/bin/postcss -> /usr/lib/node_modules/postcss-cli/bin/postcss
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/postcss-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```
不知道这个会不会有影响...

你有没有兴趣看看这个问题? 还是说我的安装方式有问题? 
我 Container 里的 nodejs 是8.11.4

多谢啦!

**Comment by riveryc** [comment]
如果这个问题没法通过这样的方式解决的话, 我只能在本地 hugo 把 resources 文件夹 build 出来, 然后把它从 gitignore 移除, 让它在 container 里直接 hugo based on existing resources folder...

有什么建议吗? 

BTW: 这个是我现在的 hugo folder 下的 gitignore:
```
# Output folder
/public

#Cache folder
/resources
```

**Comment by laozhu** [comment]
@riveryc docker 没玩过呀，你可以试试 caddy + hugo 的组合，配合 github 的 webhook 你只要本地推到 github 上就自动上线了，我很久以前折腾过，现在工作忙没时间搞了。

<https://laozhu.me/post/deploy-blog-with-caddy-and-hugo/>

**Comment by riveryc** [comment]
用 caddy 是一个好思路, 直接把 Certificate 的问题解决了. 可是就没法用 Github 或者 Gitlab 的 pages 的静态页面存储功能了... 
用 caddy 需要有一个虚拟机或者用 Container 来做服务了... 
也不是不成, 就是得找地方花钱去了~ 哈哈
