### ISSUE TITLE
Social media links have no text for screen readers

### ISSUE THREAD

**Issue by zersiax** [laozhu/hugo-nuo#95]
Hi,

I actually really like your theme and would love to use it for my blog/personal website. However, the social media icons currently have no textual label for screen readers. Could you have a look at adding this?

**Comment by laozhu** [comment]
@zersiax Thank you for your suggestion, it's a great suggestion.

I learned a11y from Google and make 100 points with lighthouse a11y audits now.

![image](https://user-images.githubusercontent.com/1212457/50229704-da842c00-03e5-11e9-93f7-d1f140e4d8b0.png)

Maybe I will learn something about PWA and support it next time 😂

**Comment by zersiax** [comment]
All you really need to do is add an aria-label="Twitter", aria-label="Facebook" etc to fix the issue. If you don't have time I can probably make a pull request tomorrow.

**Comment by laozhu** [comment]
@zersiax fixed, and an `aria-hidden="true"` to the icon element.

I referred to this great post:

<https://fontawesome.com/how-to-use/on-the-web/other-topics/accessibility>
