### ISSUE TITLE
[Feature request] Support for Valine

### ISSUE THREAD

**Issue by VincentTam** [laozhu/hugo-nuo#96]
[Valine](https://valine.js.org/) is a JS commenting system _without_ backend licensed under GPLv2.  It's quite simple to implement.  As a result, it has attracted many netizens.

As can be seen in [Jekyll TeXt Theme](https://github.com/kitian616/jekyll-TeXt-theme), it's not so difficult to implement.

**Comment by laozhu** [comment]
@VincentTam Looks nice, I will add to feature list later.

**Comment by enersto** [comment]
how could I ADD valine by myself? and is that good to add code on \hugo-nuo\layouts\partials\gitment ?

**Comment by laozhu** [comment]
Busy these days 🐝
Welcome PR for comment system refactoring.

👉 <https://github.com/laozhu/hugo-nuo/pull/104#issuecomment-451965721>
