### ISSUE TITLE
我电脑chorme footer不显示

### ISSUE THREAD

**Issue by zhanglihow** [laozhu/hugo-nuo#99]
fireFox浏览器会显示 
电脑分辨率是 1600*900
手机浏览器也会显示 手机分辨率是 2248*1080的
请问可以在哪里设置吗？

**Comment by laozhu** [comment]
@zhanglihow 桌面就是不显示的，没有想到好的显示方式。

#86 类似。

**Comment by zstcode** [comment]
![default](https://user-images.githubusercontent.com/17093158/51439353-e9674280-1cf3-11e9-9c24-e5590a85be3b.png)
感觉这样再调一下间距也还行吧
